######################################

# This script defines the project pipeline - it specifys the execution orders for all the code in this
# repo using a series of actions.

######################################

version: '3.0'

expectations:
  population_size: 1000000

actions:

  # Extract data for study population flow chart
  generate_study_population_flow_chart_data:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_flow_chart
    outputs:
      highly_sensitive:
        cohort: output/input_flow_chart.csv

  # Calculate numbers for study population flow chart
  flow_chart:
    run: r:latest -e 'rmarkdown::render("analysis/R/Markdown/Study_definition_flow_chart.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
    needs: [generate_study_population_flow_chart_data]
    outputs:
      moderately_sensitive:
        html: output/Study_definition_flow_chart.html
        
  # Extract study data
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv
        
  # Process data
  data_process_all:
    run: r:latest analysis/R/Scripts/00_process_data.R
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        data1: output/data/data_all.rds
        
  # Summarise data
  data_properties_all:
    run: r:latest analysis/R/Scripts/01_data_properties.R output/data/data_all.rds output/data_properties
    needs: [data_process_all]
    outputs:
      moderately_sensitive:
        datasummary: output/data_properties/data_all*.txt
        
  # Practice ID summaries
  practice_id:
    run: r:latest -e 'rmarkdown::render("analysis/R/Markdown/Data_summaries_practices.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        html: output/Data_summaries_practices.html
        
  # Models
  cox_models:
    run: r:latest analysis/R/Scripts/02_Models.R
    needs: [generate_study_population, data_process_all]
    outputs:
      highly_sensitive :
        models: output/models/testing/mod*.rds
        
  cox_models_sub:
    run: r:latest analysis/R/Scripts/02_Models_sub_test.R
    needs: [generate_study_population, data_process_all]
    outputs:
      highly_sensitive :
        models: output/models/testing/mod_test*.rds
        

  # Models summaries
  # cox_models_summaries:
  #   run: r:latest -e 'rmarkdown::render("analysis/R/Markdown/Model_comparisons.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
  #   needs: [generate_study_population, data_process_all, cox_models]
  #   outputs:
  #     moderately_sensitive:
  #       html: output/Model_comparisons.html
        
  # Models
  cox_model_final:
    run: r:latest analysis/R/Scripts/03_Final_model.R
    needs: [generate_study_population, data_process_all]
    outputs:
      highly_sensitive :
        models: output/models/mod*.rds
      moderately_sensitive:
        tables: output/models/tab*.html
        data: output/models/tab*.csv
        plots: output/models/plot*.svg



