######################################

# This script defines the project pipeline - it specifys the execution orders for all the code in this
# repo using a series of actions.

######################################

version: '3.0'

expectations:
  population_size: 1000000

actions:

  # Extract data for study population flow chart
  generate_study_population_flow_chart_data:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_flow_chart
    outputs:
      highly_sensitive:
        cohort: output/input_flow_chart.csv

  # Calculate numbers for study population flow chart
  flow_chart:
    run: r:latest -e 'rmarkdown::render("analysis/R/Markdown/Study_definition_flow_chart.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
    needs: [generate_study_population_flow_chart_data]
    outputs:
      moderately_sensitive:
        html: output/Study_definition_flow_chart.html
        
  # Extract study data
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv
