---
title: "Model comparisons"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE, warning= FALSE, message= FALSE}
# Preliminaries ----

## Import libraries
library('tidyverse')
library('lubridate')
library('survival')
library('coxme')
library('gtsummary')
library('gt')
library("survminer")
#library('ehahelper')

## Import processed data
data_tte <- read_rds(here::here("output", "data", "data_all.rds"))

## Converts logical to integer so that model coefficients print nicely in gtsummary methods
data_cox <- data_tte %>%
  mutate(
    across(
      where(is.logical),
      ~.x*1L
    )
  )

## Import models data
coxmod1 <- read_rds(here::here("output", "models", "mod_coxph_adj.rds"))
coxmod1b <- read_rds(here::here("output", "models", "mod_coxph_adjb.rds"))
coxmod2 <- read_rds(here::here("output", "models", "mod_coxme_adj.rds"))

## Function to test random effects
TestRanef <- function(coxphModel,coxmeModel) {

    if (!class(coxphModel) == "coxph" | !class(coxmeModel) == "coxme") {
        stop("Wrong models")
    }

    ## Degrees of freedom
    coxphDf <- sum(!is.na(coef(coxphModel)))
    coxmeDf <- coxmeModel$df
    names(coxmeDf) <- c("Integrated","Penalized")
    ## DF differnces
    dfDiff <- coxmeDf - coxphDf


    ## Log likelihodds
    coxphLogLik <- coxphModel$loglik[2]
    coxmeLogLik <- coxmeModel$loglik + c(0, 0, coxmeModel$penalty)
    coxmeLogLik <- coxmeLogLik[2:3]
    ## -2 logLik difference
    logLikNeg2Diff <- c(-2 * (coxphLogLik - coxmeLogLik["Integrated"]),
                        -2 * (coxphLogLik - coxmeLogLik["Penalized"]))

    ## p-values
    pVals <- pchisq(q = logLikNeg2Diff, df = dfDiff, lower.tail = FALSE)

    ## Combine
    outDf <- data.frame(dfDiff, logLikNeg2Diff, pVals)
    colnames(outDf) <- c("df diff", "-2logLik diff", "p-values")
    outDf
}
```

## Testing proportional Hazards assumption

### Adjusted cox ph model
```{r, echo = FALSE, warning= FALSE, message= FALSE}
test.ph <- cox.zph(coxmod1)
test.ph
```

### Adjusted cox ph model
```{r, echo = FALSE, warning= FALSE, message= FALSE}
test.ph <- cox.zph(coxmod1b)
test.ph
```

### Adjusted cox me model
```{r, echo = FALSE, warning= FALSE, message= FALSE}
test.ph <- cox.zph(coxmod2)
test.ph
```


## Testing for random effects (using integrated log likelihook)
```{r, echo = FALSE, warning= FALSE, message= FALSE}
anova(coxmod1, coxmod1b)
anova(coxmod1, coxmod2)
anova(coxmod1, coxmod1b)

TestRanef(coxmod1, coxmod2)
```